const actionsTypesListaParche = {
  LOAD_SUCCESS_LISTA_PARCHE: 'LOAD_SUCCESS_LISTA_PARCHE',
  LOAD_FAILURE_LISTA_PARCHE: 'LOAD_FAILURE_LISTA_PARCHE',
  LOADING_LISTA_PARCHE: 'LOADING_LISTA_PARCHE'
}

export default actionsTypesListaParche
