const actionsTypesExample = {
  LOADING_SUCCESS_MY_EXAMPLE: 'LOADING_SUCCESS_MY_EXAMPLE',
  LOAD_SUCCESS_MY_EXAMPLE: 'LOAD_SUCCESS_MY_EXAMPLE',
  LOAD_FAILURE_MY_EXAMPLE: 'LOAD_FAILURE_MY_EXAMPLE'
}

export default actionsTypesExample
