const actionsTypesEliminarParche = {
    LOAD_SUCCESS_ELIMINAR_PARCHE: 'LOAD_SUCCESS_ELIMINAR_PARCHE',
    LOAD_FAILURE_ELIMINAR_PARCHE: 'LOAD_FAILURE_ELIMINAR_PARCHE',
    LOADING_ELIMINAR_PARCHE: 'LOADING_ELIMINAR_PARCHE',
    LOAD_ELIMINAR_PARCHE: 'LOAD_ELIMINAR_PARCHE'
  }
  
  export default actionsTypesEliminarParche