const actionsTypesEditarParche = {
  LOAD_SUCCESS_EDITAR_PARCHE: 'LOAD_SUCCESS_CREAR_PARCHE',
  LOAD_FAILURE_EDITAR_PARCHE: 'LOAD_FAILURE_CREAR_PARCHE',
  LOADING_EDITAR_PARCHE: 'LOADING_CREAR_PARCHE',
  LOAD_ACTUALIZAR_DIRECCION: 'LOAD_ACTUALIZAR_DIRECCION'
}

export default actionsTypesEditarParche
