const actionsTypesCrearParche = {
  LOAD_SUCCESS_CREAR_PARCHE: 'LOAD_SUCCESS_CREAR_PARCHE',
  LOAD_FAILURE_CREAR_PARCHE: 'LOAD_FAILURE_CREAR_PARCHE',
  LOADING_CREAR_PARCHE: 'LOADING_CREAR_PARCHE'
}

export default actionsTypesCrearParche
