const actionsTypesUnParche = {
  LOAD_SUCCESS_UN_PARCHE: 'LOAD_SUCCESS_UN_PARCHE',
  LOAD_FAILURE_UN_PARCHE: 'LOAD_FAILURE_UN_PARCHE',
  LOADING_UN_PARCHE: 'LOADING_UN_PARCHE'
}

export default actionsTypesUnParche
