const actionsTypesFiltrarListaParches = {
  FILTRAR_LISTA_PARCHES: 'FILTRAR_LISTA_PARCHES',
  SELECT_VALUE_CATEGORIA: 'SELECT_VALUE_CATEGORIA',
  INPUT_VALUE_NOMBRE: 'INPUT_VALUE_NOMBRE',
  BUSQUEDA_ERRONEA: 'BUSQUEDA_ERRONEA'
}

export default actionsTypesFiltrarListaParches
