const actionsTypesDeshabilitarParche = {
  LOAD_SUCCESS_DESHABILITAR_PARCHE: 'LOAD_SUCCESS_DESHABILITAR_PARCHE',
  LOAD_FAILURE_DESHABILITAR_PARCHE: 'LOAD_FAILURE_DESHABILITAR_PARCHE',
  LOADING_DESHABILITAR_PARCHE: 'LOADING_CREAR_DESHABILITAR'
}

export default actionsTypesDeshabilitarParche
