const actionsTypesFiltrarMisParches = {
  FILTRAR_MIS_PARCHES: 'FILTRAR_MIS_PARCHES',
  SELECT_VALUE_CATEGORIAS: 'SELECT_VALUE_CATEGORIAS',
  INPUT_VALUE_NOMBRE_PARCHE: 'INPUT_VALUE_NOMBRE_PARCHE',
  BUSQUEDA_ERRONEA: 'BUSQUEDA_ERRONEA'
}

export default actionsTypesFiltrarMisParches
