const actionsTypesMisParches = {
  LOAD_SUCCESS_MIS_PARCHES: 'LOAD_SUCCESS_MIS_PARCHES',
  LOAD_FAILURE_MIS_PARCHES: 'LOAD_FAILURE_MIS_PARCHES',
  LOADING_MIS_PARCHES: 'LOADING_MIS_PARCHES'
}

export default actionsTypesMisParches
