
const authTypes = {
  INICIAR_SESION: 'INICIAR_SESION',
  CERRAR_SESION: 'CERRAR_SESION',
  SESION_INICIADA: 'SESION_INICIADA',
  ERROR_INICIAR_SESION: 'ERROR_INICIAR_SESION',
  EXITO_INICIO_SESION: 'EXITO_INICIO_SESION'
}

export default authTypes
